// src/pages/Home.tsx
import React from 'react'
import GameHeader from '../components/GameHeader'
import Board from '../components/Board'
import BoardSelected from '../components/BoardSelected'
import Rules from '../components/Rules'
import { useGameStore } from '../store/useGameStore'

const Home: React.FC = () => {
  const userChoice = useGameStore((state) => state.userChoice)

  return (
    <div className="game">
      <GameHeader />
      {!userChoice ? <Board /> : <BoardSelected />}
      <Rules />
    </div>
  )
}

export default Home

// src/pages/Home.vue
<template>
  <div class="game">
    <game-header />
    <board v-if="!userChoice" />
    <board-selected v-if="userChoice" />
    <rules />
  </div>
</template>

<script>
// @flow

import GameHeader from '@/components/GameHeader'
import Board from '@/components/Board'
import BoardSelected from '@/components/BoardSelected'
import Rules from '@/components/Rules'

import { get } from 'vuex-pathify'

export default {
  name: 'Home',
  components: {
    GameHeader,
    Board,
    BoardSelected,
    Rules
  },
  computed: {
    userChoice: get('game/userChoice')
  }
}
</script>
