// src/components/Board.vue
<template>
  <div class="board">
    <div class="board-bg"></div>
    <div class="icon-rock"></div>
    <div class="icon-paper"></div>
    <div class="icon-scissors"></div>
    <div class="icon-lizard"></div>
    <div class="icon-spock"></div>
  </div>
</template>

<script>
// @flow

export default {
  name: 'Board'
}
</script>

// src/components/Board.tsx
import { useGameStore, GameChoice } from '@/store/useGameStore'

const Board = () => {
  const setUserChoice = useGameStore((state) => state.setUserChoice)

  const handleSelection = (choice: GameChoice) => {
    setUserChoice(choice)
  }

  return (
    <div className="board">
      <div className="board-bg"></div>
      <div
        className="icon icon-scissors"
        onClick={() => handleSelection('scissors')}
      ></div>
      <div
        className="icon icon-paper"
        onClick={() => handleSelection('paper')}
      ></div>
      <div
        className="icon icon-rock"
        onClick={() => handleSelection('rock')}
      ></div>
      <div
        className="icon icon-lizard"
        onClick={() => handleSelection('lizard')}
      ></div>
      <div
        className="icon icon-spock"
        onClick={() => handleSelection('spock')}
      ></div>
    </div>
  )
}

export default Board
