// src/components/GameHeader.vue
<template>
  <div class="header">
    <div class="header-logo">
      <img src="@/assets/images/logo-bonus.svg" alt="logo" />
    </div>
    <div class="header-score">
      <div class="score-text">score</div>
      <div class="score-number">12</div>
    </div>
  </div>
</template>

<script>
// @flow

export default {
  name: 'GameHeader'
}
</script>

// src/components/GameHeader.tsx
import React from 'react'
import { useGameStore } from '../store/useGameStore'

const GameHeader: React.FC = () => {
  const score = useGameStore((state) => state.score)

  return (
    <div className="header">
      <div className="header-logo">
        <img src="./assets/images/logo-bonus.svg" alt="logo" />
      </div>
      <div className="header-score">
        <div className="score-text">score</div>
        <div className="score-number">{score}</div>
      </div>
    </div>
  )
}

export default GameHeader
