// src/components/Rules.vue
<template>
  <div class="rules">
    <div class="btn-rules" @click="showModal = !showModal">rules</div>

    <transition>
      <div v-if="showModal" class="rules-modal">
        <div class="modal-title">rules</div>
        <div class="modal-image">
          <img src="@/assets/images/image-rules-bonus.svg" alt="rules" />
        </div>
        <div class="modal-close" @click="showModal = false">
          <img src="@/assets/images/icon-close.svg" alt="rules" />
        </div>
      </div>
    </transition>
  </div>
</template>

<script>
// @flow

export default {
  name: 'Rules',
  data() {
    return {
      showModal: false
    }
  }
}
</script>

// src/components/Rules.tsx
import { useState } from 'react'

function Rules() {
  const [showModal, setShowModal] = useState(false)

  return (
    <div className="rules">
      <div className="btn-rules" onClick={() => setShowModal(!showModal)}>
        rules
      </div>

      {showModal && (
        <div className="rules-modal">
          <div className="modal-title">rules</div>
          <div className="modal-image">
            <img src="/assets/images/image-rules-bonus.svg" alt="rules" />
          </div>
          <div className="modal-close" onClick={() => setShowModal(false)}>
            <img src="/assets/images/icon-close.svg" alt="close" />
          </div>
        </div>
      )}
    </div>
  )
}

export default Rules
